name: GitHub Clang Format
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]

jobs:
  Clang-Format-File:
  runs-on: ubuntu-latest
  steps:
    - name: Cat File Test Before Clang Format
      run: cat testClangFormat.c
    # - name: Run Clang Format
    #  run: clang-format -i testClangFormat.c
    - name: Cat File Test After Clang Format
      run: cat testClangFormat.c
