name: GitHub Clang Format
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]

jobs:
  Clang-Format-File:
    runs-on: ubuntu-latest
    steps:
      - name: LS
        run: |
          ls ${{ github.workspace }}
      - name: path
        run: |
          pwd
      - name: LS
        run: |
          ls ../
      - name: tree
        run: |
          tree ../
      - uses: pCYSl5EDgo/cat@master
        with:
          path: testClangFormat.c
      - name: Cat File Test Before Clang Format
        run: cat $TEXT
        env:
          TEXT: ${{ steps.testClangFormat.c.outputs.text }}
      # - name: Run Clang Format
      #  run: clang-format -i testClangFormat.c
      - name: Cat File Test After Clang Format
        run: cat ./testClangFormat.c
